# not for production use !
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      #- ./data/db:/var/lib/postgresql/data # I couldn't get this to work with docker for windows
      - pgNotesData:/var/lib/postgresql/data # docker for windows work-around. May need to re-run after creating volume to fix errors.
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - AUTHY_SID=0 # edit this
      - AUTHY_SECRET=0 # edit this
      - AUTHY_SERVICE=VA67f1b0ce60f032806556659b8b5fa76d
    depends_on:
      - db

volumes:
  pgNotesData: