# Generated by Django 3.2.10 on 2021-12-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='tasks',
        ),
    ]
