# Generated by Django 3.2.10 on 2021-12-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
